name:                spire
version:             0.1.0.0
github:              "githubuser/spire"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spire#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1
- mtl >= 2.2.2
- split


library:
  source-dirs: src

executables:
  tic-tac-toe-exe:
    main:                 TicTacToe.hs
    source-dirs:          app
    ghc-options:
    - -main-is            TicTacToe
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spire

  connect-four-exe:
    main:                ConnectFour.hs
    source-dirs:         app
    ghc-options:
    - -main-is           ConnectFour
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spire

  chess-exe:
    main:                 Chess.hs
    source-dirs:          app
    ghc-options:
    - -main-is            Chess
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spire

  othello-exe:
    main:                 Othello.hs
    source-dirs:          app
    ghc-options:
    - -main-is            Othello
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spire
